### ISSUE TITLE
Weekly Scrum - March 11

### ISSUE THREAD

**Issue by omarimran2000** [omarimran2000/COVID-Contract-Tracing#10]

**Comment by omarimran2000** [comment]
I created the ContactCase Model (Issue #3), the REST Controller for the Contact Case (Issue #9 ) and populating the HTML views using JavaScript (Issue #8 ). Next week, I will look at implementing the public health unit model(Issue #29) so that a login can be implemented for adding new COVID/contact cases. Nothing is holding me back at the moment.

**Comment by wyosief** [comment]
I created the CovidCase Model (Issue #4), the REST Controller for the Covid Case (Issue #7), the UML Class Diagram (Issue #27), and the README (Issue #16). Next week, I will look at implementing a login page for the Public Health Unit users (Issue #30). Currently, there is nothing holding me back.

**Comment by BraxtonMartin0** [comment]
I created the HTML page and form for the contacts to be used by internal staff. (Issue #5 ) and created test cases (Issue #15) for the COVID Case Controller (Issue #9 ). Next week, I will look into adding CSS to the HTML pages (Issue #24). Currently, there is nothing holding me back.

**Comment by benbaggs46** [comment]
I created test cases for the Contact Case Controller (Issue #13) and created tests for the forms shown by the web controller. Next week, I will create a REST Controller to be used by the Public Health People (Issue #31). Currently, there is nothing holding me back.

**Comment by erica925** [comment]
I created the HTML page for the daily questionnaire filled out by the contacts (Issue #6) and the ER diagram (Issue #17). Next week, I will add the error pages (Issue #23). Nothing is holding me back at the moment.
