### ISSUE TITLE
Weekly Scrum - March 25

### ISSUE THREAD

**Issue by omarimran2000** [omarimran2000/COVID-Contract-Tracing#39]

**Comment by omarimran2000** [comment]
I created the username portion of User (Issue #30), developed the error tracking in the questionnaire (Issue #29), Created the Header (Issue #38) and updated the ER diagram (Issue #45). Next iteration, I will look to Combine the Login and Form pages to increase Security (Issue #48)

**Comment by wyosief** [comment]
I created the password portion of User (Issue #31), created tables for the output of the Public Health Form (Issue #36), the CSS styling of the Login page (Issue #47), and updated the UML Class diagram (Issue #44). Next iteration, I will look into adding the Type of Help Needed feature (Issue #50). Nothing is holding me back at the moment.

**Comment by erica925** [comment]
I created the error message on the contact form (Issue #23) and updated the readme for this milestone (Issue #46). Next iteration I will create the error message for searching the COVID cases (Issue #51). Nothing is holding me back at the moment.

**Comment by BraxtonMartin0** [comment]
I added CSS customizations for the main menu (Issue #43 ) and for the contact case form (Issue #24 ). Next iteration, I will work on registering users (Issue #53 ). Currently there is nothing holding me back.

**Comment by benbaggs46** [comment]
Next iteration, I will create CSS for the Contact Case Questionnaire (Issue #37). Currently, there is nothing holding me back.
