### ISSUE TITLE
Weekly Scrum - April 8 

### ISSUE THREAD

**Issue by omarimran2000** [omarimran2000/COVID-Contract-Tracing#66]

**Comment by BraxtonMartin0** [comment]
For this final sprint, I completed the password strength checker (Issue #53 ), username error checking (Issue #80 ) and added CSS to the home page to make it split screen with links to the correct pages (Issue #65 ).

**Comment by erica925** [comment]
I added the error message for when no covid case with the specified case id is found (Issue #51), updated the styling of the questionnaire page (Issue #37), and updated the readme file (Issue #68)

**Comment by omarimran2000** [comment]
In the final sprint, I worked on adding the not quarantining feature (Issue #49), stopping users from completing the questionnaire multiple times (Issue #61), creating the username feature for registering public health users (Issue #71), allowing users to see their password (Issue #77) and updating the ER diagram (Issue #70).

**Comment by wyosief** [comment]
In the final sprint, I added the Type of Support Needed feature (Issue #50), updated the styling of the header (Issue #64), and updated the UML Class Diagram (Issue #69).
